This is a matrix multiplication code using normal method

In [1]:
X = [[2,4,4],
     [4,3,2],
     [2,4,3]]
Y = [[2,4,3],
     [4,2,4],
     [3,5,1]]
Result = [[0,0,0],
          [0,0,0],
          [0,0,0]]
for i in range(len(X)):
        for j in range(len(Y[0])):
                for k in range(len(Y)):
                        Result[i][j] += X[i][k] * Y[k][j]
print("The Multiplication of matrix is :")
for r in Result:
        print(r)


The Multiplication of matrix is :
[32, 36, 26]
[26, 32, 26]
[29, 31, 25]


Ths is Matrix multiplication code using numpy

In [2]:
import numpy as np

mat1 = ([2,4,1],[2,4,6],[3,2,1])
mat2 = ([2,4,7],[1,4,6],[2,6,3])

res = np.dot(mat1,mat2)

print("The Multiplication of matrix is :")
print(res)

The Multiplication of matrix is :
[[10 30 41]
 [20 60 56]
 [10 26 36]]


**Operations on Matrices**

In [3]:
# Rank Of Matrix

import numpy as np

Matrix1 = np.array([[2,3,5],[2,1,3],[2,1,1]])

print("The rank of a matrix is : ",np.linalg.matrix_rank(Matrix1))

The rank of a matrix is :  3


In [5]:
# without numpy

# def findRank(matrix):
#     def swap(matrix, row1, row2):
#         matrix[row1], matrix[row2] = matrix[row2], matrix[row1]

#     n = len(matrix)
#     m = len(matrix[0])
#     rank = 0

#     for row in range(n):
#         if rank >= m:
#             break
#         if matrix[row][rank] != 0:
#             for i in range(row + 1, n):
#                 if matrix[i][rank] != 0:
#                     factor = matrix[i][rank] / matrix[row][rank]
#                     for j in range(rank, m):
#                         matrix[i][j] -= factor * matrix[row][j]
#             rank += 1
#         else:
#             for i in range(row + 1, n):
#                 if matrix[i][rank] != 0:
#                     swap(matrix, row, i)
#                     break
#             else:
#               rank += 1
#               row -= 1

#     return rank



def swap_rows(matrix, row1, row2):
    matrix[row1], matrix[row2] = matrix[row2], matrix[row1]

def findRank(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    rank = 0

    for r in range(rows):
        if matrix[r][rank] != 0:
            for i in range(r + 1, rows):
                factor = matrix[i][rank] / matrix[r][rank]
                for j in range(rank, cols):
                    matrix[i][j] -= factor * matrix[r][j]
            rank += 1
        else:
            for i in range(r + 1, rows):
                if matrix[i][rank] != 0:
                    swap_rows(matrix, r, i)
                    rank += 1
                    break

    return rank



def input_matrix():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    matrix = []
    for i in range(rows):
        row = list(map(float, input().split()))
        matrix.append(row)

    return matrix

matrix = input_matrix()


rank = findRank(matrix)

print("Rank of the matrix:", rank)


# Nullity of a matrix

nullity = len(matrix[0])- rank
print("Nullity of matrix is : ",nullity)

Enter the number of rows:  2
Enter the number of columns:  2
 1 2
 1 4


Rank of the matrix: 2
Nullity of matrix is :  0


In [6]:
# Order of a matrix

def matrix_order(matrix):
    if not matrix or not matrix[0]:
        return (0, 0)
    return (len(matrix), len(matrix[0]))



matrix = [
    [2,4,1],
    [6,9,2],
    [3,5,1]
]

order = matrix_order(matrix)
print("Order of the matrix:", order)

Order of the matrix: (3, 3)


In [ ]:
# Determinant of a matrix

def det(matrix):
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    deter = 0
    for i in range(len(matrix)):
        sub_matrix = [row[:i] + row[i+1:] for row in matrix[1:]]
        deter += ((-1) ** i) * matrix[0][i] * det(sub_matrix)

    return deter

matrix = ([
    [2,7,1],
    [6,3,2],
    [3,5,1]
])

det = det(matrix)
print("Determinnt of the matrix:", det)



# Singular matrix

if(det==0):
  print("The matrix is singular")




# Non-Singular matrix

if(det!=0):
  print("The matrix is Non-singular")



# Trace of a matrix

sum=0
for i in range(len(matrix)):
  sum += matrix[i][i]


print("Trace of matrix is : ",sum)



Determinnt of the matrix: 7
The matrix is Non-singular
Trace of matrix is :  6


**Inverse of matrix**

In [ ]:
def minor(matrix, row, col):
    return [[matrix[i][j] for j in range(len(matrix[i])) if j != col] for i in range(len(matrix)) if i != row]

def determinant(matrix):
    n = len(matrix)
    if n == 1:
        return matrix[0][0]
    if n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    return sum(((-1) ** c) * matrix[0][c] * determinant(minor(matrix, 0, c)) for c in range(n))

def cofactor(matrix):
    n = len(matrix)
    return [[((-1) ** (r + c)) * determinant(minor(matrix, r, c)) for c in range(n)] for r in range(n)]

def transpose(matrix):
    return [list(row) for row in zip(*matrix)]

def matrix_inverse(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError("Matrix is singular and cannot be inverted.")
    cofactors = cofactor(matrix)
    adjugate = transpose(cofactors)
    return [[element / det for element in row] for row in adjugate]






matrix = ([
    [2,4,1],
    [6,8,2],
    [3,5,1]
])

inverse = matrix_inverse(matrix)
print("Inverse of the matrix:")
for row in inverse:
    print(row)


Inverse of the matrix:
[-1.0, 0.5, 0.0]
[0.0, -0.5, 1.0]
[3.0, 1.0, -4.0]


**Write a Python function that verifies the solution of the system AX=b**

In [ ]:
# prompt: Write a Python function that verifies the solution of the system AX=b write the code without using numpy

def verify_solution(A, X, b):

  rows_A = len(A)
  cols_A = len(A[0])
  if rows_A != len(b) or cols_A != len(X):
    raise ValueError("Dimensions of A, X, and b are not compatible for matrix multiplication.")

  AX = [[0] * 1 for _ in range(rows_A)]
  for i in range(rows_A):
    for j in range(cols_A):
      AX[i][0] += A[i][j] * X[j]

  for i in range(len(AX)):
    if abs(AX[i][0] - b[i]) > 1e-6:
      return False

  return True


A = [[2, 3], [4, 1]]
X = [1, 2]
b = [8, 6]

if verify_solution(A, X, b):
  print("The solution is correct.")
else:
  print("The solution is incorrect.")


**Write a Python program that solves the system of linear equations  for ax=b**

In [ ]:
def solve(A, b):
    n = len(A)
    matrix = [row[:] + [b[i]] for i, row in enumerate(A)]

    for i in range(n):
        pivot = matrix[i][i]
        if pivot == 0:
            for j in range(i + 1, n):
                if matrix[j][i] != 0:
                    matrix[i], matrix[j] = matrix[j], matrix[i]
                    pivot = matrix[i][i]
                    break
            else:
                return None

        for j in range(n + 1):
            matrix[i][j] /= pivot

        for j in range(n):
            if i != j:
                factor = matrix[j][i]
                for k in range(n + 1):
                    matrix[j][k] -= factor * matrix[i][k]

    x = [row[-1] for row in matrix]
    return x


# Example usage:
A = [[2, 1, -1],
     [-3, -1, 2],
     [-2, 1, 2]]
b = [8, -11, 2]

solution = solve(A, b)

if solution:
    print("Solution:", solution)
else:
    print("The system is either inconsistent")


Solution: [-3.0, 8.0, -6.0]


**Write a Python program to find the inverse of matrix A  and use it to solve for x in  Ax=b**

In [7]:
def minor(matrix, row, col):
    return [[matrix[i][j] for j in range(len(matrix[i])) if j != col] for i in range(len(matrix)) if i != row]

def determinant(matrix):
    n = len(matrix)
    if n == 1:
        return matrix[0][0]
    if n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    return sum(((-1) ** c) * matrix[0][c] * determinant(minor(matrix, 0, c)) for c in range(n))

def cofactor(matrix):
    n = len(matrix)
    return [[((-1) ** (r + c)) * determinant(minor(matrix, r, c)) for c in range(n)] for r in range(n)]

def transpose(matrix):
    return [list(row) for row in zip(*matrix)]

def matrix_inverse(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError()
    cofactors = cofactor(matrix)
    adjugate = transpose(cofactors)
    return [[element / det for element in row] for row in adjugate]

def matrix_multiply(A, X):
    rows_A = len(A)
    cols_A = len(A[0]) if rows_A > 0 else 0
    rows_X = len(X)
    cols_X = len(X[0]) if rows_X > 0 else 0

    if cols_A != rows_X:
        raise ValueError()

    result = [[0] * cols_X for _ in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_X):
            for k in range(cols_A):
                result[i][j] += A[i][k] * X[k][j]

    return result


A = [[2, 1, -1],
     [-3, -1, 2],
     [-2, 1, 2]]
b = [[8], [-11], [2]]

try:
    inverse_A = matrix_inverse(A)
    x = matrix_multiply(inverse_A, b)
    print("Solution x:")
    for row in x:
        print(row)
except ValueError:
    print("The matrix is singular")

Solution x:
[-3.0]
[8.0]
[-6.0]


In [12]:
def input_matrix():
    rows = int(input("Enter No. of rows : "))
    cols = int(input("Enter No. of cols : "))

    matrix = []
    for i in range(rows):
        row = list(map(int,input().split()))
        matrix.append(row)

    return matrix


matrix = input_matrix()
# print(matrix)

for row in matrix:
    print(row)
    

Enter No. of rows :  3
Enter No. of cols :  3
 1 2 3
 4 5 6
 7 8 9


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
